// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    AppBar: typeof import("./src/components/AppBar/AppBar.vue")["default"];
    Footer: typeof import("./src/components/Common/Footer.vue")["default"];
    HelloI18n: typeof import("./src/components/HelloI18n.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    I18nKey: typeof import("./src/components/template/I18nKey.vue")["default"];
    InfiniteScroll: typeof import("./src/components/template/InfiniteScroll.vue")["default"];
    LatestPages: typeof import("./src/components/Page/LatestPages.vue")["default"];
    LocaleChanger: typeof import("./src/components/LocaleChanger.vue")["default"];
    PageBrief: typeof import("./src/components/Page/PageBrief.vue")["default"];
    PageToc: typeof import("./src/components/Page/PageToc.vue")["default"];
    UserPanel: typeof import("./src/components/AppBar/UserPanel/UserPanel.vue")["default"];
  }
}

export {};
